version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - funlen
    - gocognit
    - goconst
    - godot
    - lll
    - mnd
    - nlreturn
    - tagliatelle
    - varnamelen
    - wsl
    - dupword
    - nonamedreturns
    - funcorder
    - wsl_v5
  settings:
    exhaustive:
      ignore-enum-members: stripe.*
    exhaustruct:
      exclude:
        - net/.*
        - github.com/stripe/stripe-go/.*
        - github.com/aws/aws-sdk-go-v2/.*
        - github.com/Azure/azure-sdk-for-go/sdk/storage/.*
        - github.com/twilio/twilio-go/.*
        - golang.org/x/.*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
