services:

  core:
    container_name: gofast-core
    build:
      context: ./app
      dockerfile: ./service-core/Dockerfile
      target: dev
    volumes:
      - ./app/service-core:/app/service-core
    ports:
      - 4001:4001
      - 4002:4002
    environment:
      LOG_LEVEL: debug
      HTTP_PORT: 4001
      GRPC_PORT: 4002
      DOMAIN: localhost
      TASK_TOKEN: 1234
      CORE_URL: http://localhost:4001
      ADMIN_URL: http://localhost:3001
      CLIENT_URL: http://localhost:3000
      #
      # Database
      DATABASE_PROVIDER: ${DATABASE_PROVIDER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #
      # Auth
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

  postgres:
    container_name: gofast-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
